// <auto-generated />
namespace EF6Play.Host.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addAuthor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAuthor));
        
        string IMigrationMetadata.Id
        {
            get { return "202111161350461_addAuthor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
